---
    - name: Launch instance
      ec2:
         key_name: "{{key_name}}"
         group: "{{security_group}}"
         instance_type: "{{instance_type}}"
         image: "{{image}}"
         wait: true
         region: "{{region}}"
         vpc_subnet_id: subnet-93120ce5
         instance_tags: 
                Name: ansibleTest
                Owner: Avijit 
         assign_public_ip: yes
      register: ec2
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

      tags: ec2-creation 

    - name: Create and attach a volumes
      ec2_vol:
         instance: "{{ instance }}"
         name: my_existing_volumei1_Name_tag
         volume_size: "{{ disk_size }}" 
         volume_type: "{{ volume_type }}"
         device_name: "{{ disk_name }}"
         region: "{{region}}"
      register: ec2_vol
      tags: volume-creation 
 
